### ISSUE TITLE
Pass the query params with the url

### ISSUE THREAD

**Issue by NetanelBasal** [buschtoens/express-redirect#6]
How can i pass the query params of the src url?

from `/tests/catgeory/slug?param=34&param2`
to  `/skill-center/tests/catgeory/slug?param=34&param2`

```js
app.redirect("/tests/:category/:slug", "/skill-center/tests/:category/:slug", 301);
```

**Comment by buschtoens** [comment]
Oh gosh. I haven't worked on this package in over a year. And I unfortunately didn't even notice #4.

I'll take a look at the code again and see if I can do something for you.

**Comment by NetanelBasal** [comment]
Thanks :)

**Comment by buschtoens** [comment]
Reading my old code, this is how I feel right now.

![disgusted-oh-god-why-text](https://cloud.githubusercontent.com/assets/834636/11361730/a80e0f4a-928f-11e5-994b-59cb9a0c3569.png)

I'm surprised it even works with express 4.x.

Still, I'll see what I can do. Shouldn't be too hard. :)

**Comment by NetanelBasal** [comment]
Lol

**Comment by buschtoens** [comment]
Okay, so I didn't test this. Could you `npm install buschtoens/express-redirect` and verify that it works?

```js
app.redirect("/tests/:category/:slug", "/skill-center/tests/:category/:slug", 301, true);
```

That last argument there stands for `query string append`, like with mod_rewrite.

**Comment by NetanelBasal** [comment]
I am checking

**Comment by NetanelBasal** [comment]
Working great, thanks a lot, this is very helpfull!! cheers

**Comment by buschtoens** [comment]
Happy to help.

I'll have this on npm in a few minutes. Just need to find the password for my old npm account. ;)

**Comment by NetanelBasal** [comment]
You can update maybe the docs if someone else will need this functionality, thanks again i will check npm later to update from their.

**Comment by buschtoens** [comment]
Yup, did so. Also added a deprecation notice. 8aacd54d3b167e602736284b768ddf51f946e2ef and 2eaf9689e42fb46abff95e2eef66a9fb209d8058

**Comment by NetanelBasal** [comment]
:+1:
